# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_SV.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "SV"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Avsluta      ',
    '     Exit     ': '     Avsluta     ',
    '    All in one     ': '    Allt i ett     ',
    '    Apply    ': '    Tillämpa    ',
    '    Apply     ': '    Tillämpa     ',
    '    Exit     ': '    Avsluta     ',
    '    Refresh     ': '    Uppdatera     ',
    '    Reset    ': '    Återställ    ',
    '  Batch Build   ': '  Batchbygge   ',
    '  Delete    ': '  Radera    ',
    '  Save zone  ': '  Spara zon  ',
    ' Build Imagery/DSF ': ' Bygg bilder/DSF ',
    ' Draw Water Masks  ': ' Rita vattenmasker  ',
    'Active tile': 'Aktiv ruta',
    'Aide JOSM': 'JOSM-hjälp',
    'Ajouter un pays': 'Lägg till ett land',
    'Altimétrie & Vecteurs': 'Höjddata & vektorer',
    'Altimétrie / DEM': 'Höjd / DEM',
    'Analyse…': 'Analyserar…',
    'Annuler': 'Avbryt',
    'Application ': 'Applikation ',
    'Application :': 'Applikation:',
    'Applications macOS': 'macOS-program',
    'Assemble Vector data': 'Sätt samman vektordata',
    'Assembler': 'Sätt samman',
    'Aucun patch sélectionné.': 'Ingen patch vald.',
    'Aucune vignette cochée.': 'Ingen miniatyr vald.',
    'Aéroport & Runways': 'Flygplats & banor',
    'Aéroports': 'Flygplatser',
    'Base Folder:': 'Basmapp:',
    'Bathymétrie': 'Batymetri',
    'Boost:': 'Boost:',
    'Build All': 'Bygg allt',
    'Chargement…': 'Läser in…',
    'Choisir QGIS': 'Välj QGIS',
    'Color Normalize': 'Färgnormalisering',
    'Confirmation': 'Bekräftelse',
    'Construire le cache OSM local': 'Bygg lokal OSM-cache',
    'Coordonnées et dossier de la tuile': 'Rutkoordinater och mapp',
    'Correction Patches': 'Patchkorrigering',
    'Correction patches': 'Patchkorrigering',
    'Corrections avancées': 'Avancerade korrigeringar',
    'Courbure côte': 'Kustlinjekurvatur',
    'Créer et ouvrir': 'Skapa och öppna',
    'Créer la structure': 'Skapa strukturen',
    'DSF/Imagery': 'DSF/Bilder',
    'Delete ZL zone': 'Radera ZL-zon',
    'Destination :': 'Mål:',
    'Données OSM de la tuile': 'Rutans OSM-data',
    'Dossier de sortie': 'Utdatamapp',
    'Dossier des sources': 'Källmapp',
    'Dossier enregistré.': 'Mapp sparad.',
    'Dossiers enregistrés.': 'Mappar sparade.',
    'Détail de la tuile': 'Rutdetalj',
    'Eau & Transparence': 'Vatten & transparens',
    'En attente…': 'Väntar…',
    'Enable': 'Aktivera',
    'Erase cached data': 'Radera cachelagrad data',
    'Erreur': 'Fel',
    'Erreur : ': 'Fel: ',
    'Extract Mesh ': 'Extrahera mesh ',
    'Extract overlays': 'Extrahera överlägg',
    'Exécutables Windows': 'Windows-program',
    'Fabrication Tuile': 'Rutbygge',
    'Fermer': 'Stäng',
    'Fichier PBF introuvable.': 'PBF-filen hittades inte.',
    'Fichier introuvable :': 'Filen hittades inte:',
    'Gestion des Couleurs automatisée': 'Automatiserad färghantering',
    'Gestion des Données': 'Datahantering',
    'Gestion des JPG-Patch existants': 'Befintliga JPG-patchar',
    'Imagerie': 'Bilder',
    'Imagery:': 'Bilder:',
    'Installer les Modules': 'Installera moduler',
    'JOSM introuvable.': 'JOSM hittades inte.',
    'Jpeg imagery': 'Jpeg-bilder',
    'Lacs & Rivières': 'Sjöar & floder',
    'Latitude:': 'Latitud:',
    'Load Tile Cfg ': 'Läs rutkonfig',
    'Longitude:': 'Longitud:',
    'Make GeoTiffs': 'Skapa GeoTiffs',
    'Mask data': 'Maskdata',
    'Masks': 'Masker',
    'Masques côtiers': 'Kustmasker',
    'Mesh': 'Mesh',
    'Nom du fichier :': 'Filnamn:',
    'OSM data': 'OSM-data',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Öppna i JOSM',
    'Ouvrir dans QGIS': 'Öppna i QGIS',
    "Ouvrir dans l'éditeur": 'Öppna i editor',
    'Ouvrir la racine Bathymétrie': 'Öppna Batymetri-roten',
    'Paramètres Mesh': 'Mesh-parametrar',
    'Personnel': 'Anpassad',
    'Preview': 'Förhandsvisning',
    'Preview params ': 'Förhandsvisningsparametrar ',
    'Précédent': 'Föregående',
    'Préparer un pays': 'Förbered ett land',
    'Prêt.': 'Klar.',
    'Publier': 'Publicera',
    'Qualité & Nettoyage': 'Kvalitet & rensning',
    'Rafraîchir': 'Uppdatera',
    'Ratio :': 'Förhållande:',
    'Read per tile cfg': 'Läs rutkonfig',
    'Recalculer': 'Beräkna om',
    "Recalculer l'emprise": 'Beräkna om utbredningen',
    'Reload App Cfg': 'Läs om appkonfig',
    'Restaurer': 'Återställ',
    "Restaurer l'original": 'Återställ originalet',
    'Routes': 'Vägar',
    'Réappliquer mes modifications': 'Tillämpa mina ändringar igen',
    'SUCCÈS': 'LYCKADES',
    'Saturation:': 'Mättnad:',
    'Sauvegarder mes modifications': 'Spara mina ändringar',
    'Sauvegardes': 'Säkerhetskopior',
    'Scan en cours…': 'Skannar…',
    'Shortcuts :': 'Genvägar:',
    'Source : ': 'Källa: ',
    'Strength:': 'Styrka:',
    'Suivant': 'Nästa',
    'Suppression dossier Preview': 'Radera förhandsvisningsmapp',
    'Supprimer patches sélectionnés': 'Radera valda patchar',
    'TERMINÉ.': 'KLART.',
    'Terminé.': 'Klart.',
    'Terrain & Ombrage': 'Terräng & skuggning',
    'Tile (textures)': 'Ruta (texturer)',
    'Tile (whole)': 'Ruta (hel)',
    'Timeline non disponible.': 'Tidslinje ej tillgänglig.',
    'Tous les fichiers': 'Alla filer',
    'Tout cocher': 'Markera alla',
    'Tout décocher': 'Avmarkera alla',
    'Triangulate 3D Mesh': 'Triangulera 3D-mesh',
    'Tuile active :': 'Aktiv ruta:',
    'Valider': 'OK',
    'Vector data': 'Vektordata',
    'Visualiser la tuile': 'Visa ruta',
    'Write App Cfg ': 'Spara appkonfig',
    'Write Tile Cfg': 'Spara rutkonfig',
    'Zone params ': 'Zonparametrar ',
    'Zoomlevel : ': 'Zoomnivå: ',
    'Zoomlevel:': 'Zoomnivå:',
    'bâtiments': 'byggnader',
    'indéterminée': 'odefinierad',
    'introuvable': 'hittades inte',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fi': '🇫🇮  Suomi',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_gd': '🏴  Gàidhlig',
    'language_btn_is': '🇮🇸  Íslenska',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_no': '🇳🇴  Norsk',
    'language_btn_pt': '🇵🇹  Português',
    'language_btn_sv': '🇸🇪  Svenska',
    'language_dialog_message': 'Välj språk:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Byt språk…',
    'language_menu_tools': 'Verktyg',
    'patches': 'patchar',
    'personal_provider_deleted_ok': 'Leverantör raderad.',
    'personal_provider_err_url': 'URL får inte vara tom.',
    'personal_provider_list_label': 'Mina leverantörer:',
    'routes principales': 'huvudvägar',
    'routes secondaires': 'mindre vägar',
    'trait de côte': 'kustlinje',
    'ÉCHEC': 'MISSLYCKADES',
    'ÉCHEC :': 'MISSLYCKADES:',
    'Échec.': 'Misslyckades.',
    'Écraser les fichiers de cache existants': 'Skriv över befintliga cachefiler',
    'à venir': 'kommer snart',
    '⛰ Terrain & Relief': '⛰ Terräng & höjd',
    '🌊 Côte & Masques': '🌊 Kust & masker',
    '💧 Mer & Eau': '💧 Hav & vatten',
    '📷 Imagerie & Aéroports': '📷 Bilder & flygplatser',
    '🗺 Mesh 3D': '🗺 3D-mesh',
})
