# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_FI.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "FI"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Poistu      ',
    '     Exit     ': '     Poistu     ',
    '    All in one     ': '    Kaikki yhdessä     ',
    '    Apply    ': '    Käytä    ',
    '    Apply     ': '    Käytä     ',
    '    Exit     ': '    Poistu     ',
    '    Refresh     ': '    Päivitä     ',
    '    Reset    ': '    Nollaa    ',
    '  Batch Build   ': '  Eräajo   ',
    '  Delete    ': '  Poista    ',
    '  Save zone  ': '  Tallenna alue  ',
    ' Build Imagery/DSF ': ' Rakenna kuvat/DSF ',
    ' Draw Water Masks  ': ' Piirrä vesimaskit  ',
    'Active tile': 'Aktiivinen ruutu',
    'Aide JOSM': 'JOSM-ohje',
    'Ajouter un pays': 'Lisää maa',
    'Altimétrie & Vecteurs': 'Korkeus & vektorit',
    'Altimétrie / DEM': 'Korkeus / DEM',
    'Analyse…': 'Analysoidaan…',
    'Annuler': 'Peruuta',
    'Application ': 'Sovellus ',
    'Application :': 'Sovellus:',
    'Applications macOS': 'macOS-sovellukset',
    'Assemble Vector data': 'Kokoa vektoridata',
    'Assembler': 'Kokoa',
    'Aucun patch sélectionné.': 'Ei paikkaa valittu.',
    'Aucune vignette cochée.': 'Ei pikkukuvaa valittu.',
    'Aéroport & Runways': 'Lentokenttä & kiitotiet',
    'Aéroports': 'Lentokentät',
    'Base Folder:': 'Peruskansio:',
    'Bathymétrie': 'Batymetria',
    'Boost:': 'Tehostus:',
    'Build All': 'Rakenna kaikki',
    'Chargement…': 'Ladataan…',
    'Choisir QGIS': 'Valitse QGIS',
    'Color Normalize': 'Värien normalisointi',
    'Confirmation': 'Vahvistus',
    'Construire le cache OSM local': 'Rakenna paikallinen OSM-välimuisti',
    'Coordonnées et dossier de la tuile': 'Ruudun koordinaatit ja kansio',
    'Correction Patches': 'Paikkakorjaus',
    'Correction patches': 'Paikkakorjaus',
    'Corrections avancées': 'Lisäkorjaukset',
    'Courbure côte': 'Rantaviivan kaarevuus',
    'Créer et ouvrir': 'Luo ja avaa',
    'Créer la structure': 'Luo rakenne',
    'DSF/Imagery': 'DSF/Kuvat',
    'Delete ZL zone': 'Poista ZL-alue',
    'Destination :': 'Kohde:',
    'Données OSM de la tuile': 'Ruudun OSM-data',
    'Dossier de sortie': 'Tuloskansio',
    'Dossier des sources': 'Lähdekansio',
    'Dossier enregistré.': 'Kansio tallennettu.',
    'Dossiers enregistrés.': 'Kansiot tallennettu.',
    'Détail de la tuile': 'Ruudun tiedot',
    'Eau & Transparence': 'Vesi & läpinäkyvyys',
    'En attente…': 'Odotetaan…',
    'Enable': 'Ota käyttöön',
    'Erase cached data': 'Poista välimuistidata',
    'Erreur': 'Virhe',
    'Erreur : ': 'Virhe: ',
    'Extract Mesh ': 'Pura verkko ',
    'Extract overlays': 'Pura peittokuvat',
    'Exécutables Windows': 'Windows-ohjelmat',
    'Fabrication Tuile': 'Ruudun rakennus',
    'Fermer': 'Sulje',
    'Fichier PBF introuvable.': 'PBF-tiedostoa ei löydy.',
    'Fichier introuvable :': 'Tiedostoa ei löydy:',
    'Gestion des Couleurs automatisée': 'Automaattinen värinhallinta',
    'Gestion des Données': 'Tiedonhallinta',
    'Gestion des JPG-Patch existants': 'Olemassa olevat JPG-paikat',
    'Imagerie': 'Kuvat',
    'Imagery:': 'Kuvat:',
    'Installer les Modules': 'Asenna moduulit',
    'JOSM introuvable.': 'JOSMia ei löytynyt.',
    'Jpeg imagery': 'Jpeg-kuvat',
    'Lacs & Rivières': 'Järvet & joet',
    'Latitude:': 'Leveysaste:',
    'Load Tile Cfg ': 'Lataa ruutucfg',
    'Longitude:': 'Pituusaste:',
    'Make GeoTiffs': 'Luo GeoTiffit',
    'Mask data': 'Maskidata',
    'Masks': 'Maskit',
    'Masques côtiers': 'Rannikkomaskit',
    'Mesh': 'Verkko',
    'Nom du fichier :': 'Tiedostonimi:',
    'OSM data': 'OSM-data',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Avaa JOSMissa',
    'Ouvrir dans QGIS': 'Avaa QGISissä',
    "Ouvrir dans l'éditeur": 'Avaa editorissa',
    'Ouvrir la racine Bathymétrie': 'Avaa Batymetria-juuri',
    'Paramètres Mesh': 'Verkon parametrit',
    'Personnel': 'Mukautettu',
    'Preview': 'Esikatselu',
    'Preview params ': 'Esikatseluparametrit ',
    'Précédent': 'Edellinen',
    'Préparer un pays': 'Valmistele maa',
    'Prêt.': 'Valmis.',
    'Publier': 'Julkaise',
    'Qualité & Nettoyage': 'Laatu & siivous',
    'Rafraîchir': 'Päivitä',
    'Ratio :': 'Suhde:',
    'Read per tile cfg': 'Lue ruutucfg',
    'Recalculer': 'Laske uudelleen',
    "Recalculer l'emprise": 'Laske laajuus uudelleen',
    'Reload App Cfg': 'Lataa sovelluscfg uud.',
    'Restaurer': 'Palauta',
    "Restaurer l'original": 'Palauta alkuperäinen',
    'Routes': 'Tiet',
    'Réappliquer mes modifications': 'Ota muutokseni uudelleen käyttöön',
    'SUCCÈS': 'ONNISTUI',
    'Saturation:': 'Kylläisyys:',
    'Sauvegarder mes modifications': 'Tallenna muutokseni',
    'Sauvegardes': 'Varmuuskopiot',
    'Scan en cours…': 'Skannataan…',
    'Shortcuts :': 'Pikanäppäimet:',
    'Source : ': 'Lähde: ',
    'Strength:': 'Voimakkuus:',
    'Suivant': 'Seuraava',
    'Suppression dossier Preview': 'Poista esikatselukansio',
    'Supprimer patches sélectionnés': 'Poista valitut paikat',
    'TERMINÉ.': 'VALMIS.',
    'Terminé.': 'Valmis.',
    'Terrain & Ombrage': 'Maasto & varjostus',
    'Tile (textures)': 'Ruutu (tekstuurit)',
    'Tile (whole)': 'Ruutu (koko)',
    'Timeline non disponible.': 'Aikajana ei käytettävissä.',
    'Tous les fichiers': 'Kaikki tiedostot',
    'Tout cocher': 'Valitse kaikki',
    'Tout décocher': 'Poista kaikki valinnat',
    'Triangulate 3D Mesh': 'Kolmioi 3D-verkko',
    'Tuile active :': 'Aktiivinen ruutu:',
    'Valider': 'OK',
    'Vector data': 'Vektoridata',
    'Visualiser la tuile': 'Näytä ruutu',
    'Write App Cfg ': 'Tallenna sovelluscfg',
    'Write Tile Cfg': 'Tallenna ruutucfg',
    'Zone params ': 'Alueparametrit ',
    'Zoomlevel : ': 'Zoomaustaso: ',
    'Zoomlevel:': 'Zoomaustaso:',
    'bâtiments': 'rakennukset',
    'indéterminée': 'määrittelemätön',
    'introuvable': 'ei löytynyt',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fi': '🇫🇮  Suomi',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_gd': '🏴  Gàidhlig',
    'language_btn_is': '🇮🇸  Íslenska',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_no': '🇳🇴  Norsk',
    'language_btn_pt': '🇵🇹  Português',
    'language_btn_sv': '🇸🇪  Svenska',
    'language_dialog_message': 'Valitse kieli:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Vaihda kieli…',
    'language_menu_tools': 'Työkalut',
    'patches': 'paikat',
    'personal_provider_deleted_ok': 'Palveluntarjoaja poistettu.',
    'personal_provider_err_url': 'URL ei voi olla tyhjä.',
    'personal_provider_list_label': 'Omat palveluntarjoajat:',
    'routes principales': 'päätiet',
    'routes secondaires': 'sivutiet',
    'trait de côte': 'rantaviiva',
    'ÉCHEC': 'EPÄONNISTUI',
    'ÉCHEC :': 'EPÄONNISTUI:',
    'Échec.': 'Epäonnistui.',
    'Écraser les fichiers de cache existants': 'Korvaa olemassa olevat välimuistitiedostot',
    'à venir': 'tulossa pian',
    '⛰ Terrain & Relief': '⛰ Maasto & korkeus',
    '🌊 Côte & Masques': '🌊 Rannikko & maskit',
    '💧 Mer & Eau': '💧 Meri & vesi',
    '📷 Imagerie & Aéroports': '📷 Kuvat & lentokentät',
    '🗺 Mesh 3D': '🗺 3D-verkko',
})
