# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_NO.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "NO"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Avslutt      ',
    '     Exit     ': '     Avslutt     ',
    '    All in one     ': '    Alt i ett     ',
    '    Apply    ': '    Bruk    ',
    '    Apply     ': '    Bruk     ',
    '    Exit     ': '    Avslutt     ',
    '    Refresh     ': '    Oppdater     ',
    '    Reset    ': '    Tilbakestill    ',
    '  Batch Build   ': '  Batch-bygg   ',
    '  Delete    ': '  Slett    ',
    '  Save zone  ': '  Lagre sone  ',
    ' Build Imagery/DSF ': ' Bygg bilder/DSF ',
    ' Draw Water Masks  ': ' Tegn vannmasker  ',
    'Active tile': 'Aktiv rute',
    'Aide JOSM': 'JOSM-hjelp',
    'Ajouter un pays': 'Legg til et land',
    'Altimétrie & Vecteurs': 'Høydedata & vektorer',
    'Altimétrie / DEM': 'Høyde / DEM',
    'Analyse…': 'Analyserer…',
    'Annuler': 'Avbryt',
    'Application ': 'Applikasjon ',
    'Application :': 'Applikasjon:',
    'Applications macOS': 'macOS-applikasjoner',
    'Assemble Vector data': 'Sett sammen vektordata',
    'Assembler': 'Sett sammen',
    'Aucun patch sélectionné.': 'Ingen patch valgt.',
    'Aucune vignette cochée.': 'Ingen miniatyr valgt.',
    'Aéroport & Runways': 'Flyplass & rullebaner',
    'Aéroports': 'Flyplasser',
    'Base Folder:': 'Basismappe:',
    'Bathymétrie': 'Batymetri',
    'Boost:': 'Boost:',
    'Build All': 'Bygg alt',
    'Chargement…': 'Laster…',
    'Choisir QGIS': 'Velg QGIS',
    'Color Normalize': 'Fargenormalisering',
    'Confirmation': 'Bekreftelse',
    'Construire le cache OSM local': 'Bygg lokal OSM-buffer',
    'Coordonnées et dossier de la tuile': 'Rutekoordinater og mappe',
    'Correction Patches': 'Patch-korreksjon',
    'Correction patches': 'Patch-korreksjon',
    'Corrections avancées': 'Avanserte korreksjoner',
    'Courbure côte': 'Kystlinjekurvatur',
    'Créer et ouvrir': 'Opprett og åpne',
    'Créer la structure': 'Opprett strukturen',
    'DSF/Imagery': 'DSF/Bilder',
    'Delete ZL zone': 'Slett ZL-sone',
    'Destination :': 'Mål:',
    'Données OSM de la tuile': 'Rutens OSM-data',
    'Dossier de sortie': 'Utdatamappe',
    'Dossier des sources': 'Kildemappe',
    'Dossier enregistré.': 'Mappe lagret.',
    'Dossiers enregistrés.': 'Mapper lagret.',
    'Détail de la tuile': 'Rutedetalj',
    'Eau & Transparence': 'Vann & gjennomsiktighet',
    'En attente…': 'Venter…',
    'Enable': 'Aktiver',
    'Erase cached data': 'Slett bufrede data',
    'Erreur': 'Feil',
    'Erreur : ': 'Feil: ',
    'Extract Mesh ': 'Trekk ut mesh ',
    'Extract overlays': 'Trekk ut overlegg',
    'Exécutables Windows': 'Windows-programmer',
    'Fabrication Tuile': 'Rutebygging',
    'Fermer': 'Lukk',
    'Fichier PBF introuvable.': 'PBF-fil ikke funnet.',
    'Fichier introuvable :': 'Fil ikke funnet:',
    'Gestion des Couleurs automatisée': 'Automatisk fargestyring',
    'Gestion des Données': 'Databehandling',
    'Gestion des JPG-Patch existants': 'Eksisterende JPG-patcher',
    'Imagerie': 'Bilder',
    'Imagery:': 'Bilder:',
    'Installer les Modules': 'Installer moduler',
    'JOSM introuvable.': 'JOSM ikke funnet.',
    'Jpeg imagery': 'Jpeg-bilder',
    'Lacs & Rivières': 'Innsjøer & elver',
    'Latitude:': 'Breddegrad:',
    'Load Tile Cfg ': 'Last rutekonfig',
    'Longitude:': 'Lengdegrad:',
    'Make GeoTiffs': 'Lag GeoTiffs',
    'Mask data': 'Maskedata',
    'Masks': 'Masker',
    'Masques côtiers': 'Kystmasker',
    'Mesh': 'Mesh',
    'Nom du fichier :': 'Filnavn:',
    'OSM data': 'OSM-data',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Åpne i JOSM',
    'Ouvrir dans QGIS': 'Åpne i QGIS',
    "Ouvrir dans l'éditeur": 'Åpne i editor',
    'Ouvrir la racine Bathymétrie': 'Åpne Batymetri-roten',
    'Paramètres Mesh': 'Mesh-parametere',
    'Personnel': 'Egendefinert',
    'Preview': 'Forhåndsvisning',
    'Preview params ': 'Forhåndsvisningsparametere ',
    'Précédent': 'Forrige',
    'Préparer un pays': 'Klargjør et land',
    'Prêt.': 'Klar.',
    'Publier': 'Publiser',
    'Qualité & Nettoyage': 'Kvalitet & opprydding',
    'Rafraîchir': 'Oppdater',
    'Ratio :': 'Forhold:',
    'Read per tile cfg': 'Les rutekonfig',
    'Recalculer': 'Beregn på nytt',
    "Recalculer l'emprise": 'Beregn utstrekningen på nytt',
    'Reload App Cfg': 'Last app-konfig på nytt',
    'Restaurer': 'Gjenopprett',
    "Restaurer l'original": 'Gjenopprett originalen',
    'Routes': 'Veier',
    'Réappliquer mes modifications': 'Bruk endringene mine på nytt',
    'SUCCÈS': 'VELLYKKET',
    'Saturation:': 'Metning:',
    'Sauvegarder mes modifications': 'Lagre endringene mine',
    'Sauvegardes': 'Sikkerhetskopier',
    'Scan en cours…': 'Skanner…',
    'Shortcuts :': 'Snarveier:',
    'Source : ': 'Kilde: ',
    'Strength:': 'Styrke:',
    'Suivant': 'Neste',
    'Suppression dossier Preview': 'Slett forhåndsvisningsmappe',
    'Supprimer patches sélectionnés': 'Slett valgte patcher',
    'TERMINÉ.': 'FERDIG.',
    'Terminé.': 'Ferdig.',
    'Terrain & Ombrage': 'Terreng & skyggelegging',
    'Tile (textures)': 'Rute (teksturer)',
    'Tile (whole)': 'Rute (hel)',
    'Timeline non disponible.': 'Tidslinje ikke tilgjengelig.',
    'Tous les fichiers': 'Alle filer',
    'Tout cocher': 'Merk alle',
    'Tout décocher': 'Fjern alle merker',
    'Triangulate 3D Mesh': 'Triangulér 3D-mesh',
    'Tuile active :': 'Aktiv rute:',
    'Valider': 'OK',
    'Vector data': 'Vektordata',
    'Visualiser la tuile': 'Vis rute',
    'Write App Cfg ': 'Skriv app-konfig',
    'Write Tile Cfg': 'Skriv rutekonfig',
    'Zone params ': 'Soneparametere ',
    'Zoomlevel : ': 'Zoomnivå: ',
    'Zoomlevel:': 'Zoomnivå:',
    'bâtiments': 'bygninger',
    'indéterminée': 'udefinert',
    'introuvable': 'ikke funnet',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fi': '🇫🇮  Suomi',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_gd': '🏴  Gàidhlig',
    'language_btn_is': '🇮🇸  Íslenska',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_no': '🇳🇴  Norsk',
    'language_btn_pt': '🇵🇹  Português',
    'language_btn_sv': '🇸🇪  Svenska',
    'language_dialog_message': 'Velg språk:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Endre språk…',
    'language_menu_tools': 'Verktøy',
    'patches': 'patcher',
    'personal_provider_deleted_ok': 'Leverandør slettet.',
    'personal_provider_err_url': 'URL kan ikke være tom.',
    'personal_provider_list_label': 'Mine leverandører:',
    'routes principales': 'hovedveier',
    'routes secondaires': 'mindre veier',
    'trait de côte': 'kystlinje',
    'ÉCHEC': 'MISLYKTES',
    'ÉCHEC :': 'MISLYKTES:',
    'Échec.': 'Mislyktes.',
    'Écraser les fichiers de cache existants': 'Overskriv eksisterende bufferfiler',
    'à venir': 'kommer snart',
    '⛰ Terrain & Relief': '⛰ Terreng & høyde',
    '🌊 Côte & Masques': '🌊 Kyst & masker',
    '💧 Mer & Eau': '💧 Sjø & vann',
    '📷 Imagerie & Aéroports': '📷 Bilder & flyplasser',
    '🗺 Mesh 3D': '🗺 3D-mesh',
})
