# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_ES.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "ES"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Salir      ',
    '     Exit     ': '     Salir     ',
    '    All in one     ': '    Todo en uno     ',
    '    Apply    ': '    Aplicar    ',
    '    Apply     ': '    Aplicar     ',
    '    Exit     ': '    Salir     ',
    '    Refresh     ': '    Actualizar     ',
    '    Reset    ': '    Restablecer    ',
    '  Batch Build   ': '  Construir en lote   ',
    '  Delete    ': '  Eliminar    ',
    '  Save zone  ': '  Guardar zona  ',
    ' Build Imagery/DSF ': ' Construir imágenes/DSF ',
    ' Draw Water Masks  ': ' Dibujar máscaras de agua  ',
    'Active tile': 'Tesela activa',
    'Aide JOSM': 'Ayuda de JOSM',
    'Ajouter un pays': 'Añadir un país',
    'Altimétrie & Vecteurs': 'Altimetría y vectores',
    'Altimétrie / DEM': 'Elevación / DEM',
    'Analyse…': 'Analizando…',
    'Annuler': 'Cancelar',
    'Application ': 'Aplicación ',
    'Application :': 'Aplicación:',
    'Applications macOS': 'Aplicaciones macOS',
    'Assemble Vector data': 'Ensamblar datos vectoriales',
    'Assembler': 'Ensamblar',
    'Aucun patch sélectionné.': 'Ningún parche seleccionado.',
    'Aucune vignette cochée.': 'Ninguna miniatura seleccionada.',
    'Aéroport & Runways': 'Aeropuerto y pistas',
    'Aéroports': 'Aeropuertos',
    'Base Folder:': 'Carpeta base:',
    'Bathymétrie': 'Batimetría',
    'Boost:': 'Refuerzo:',
    'Build All': 'Construir todo',
    'Chargement…': 'Cargando…',
    'Choisir QGIS': 'Elegir QGIS',
    'Color Normalize': 'Normalizar color',
    'Confirmation': 'Confirmación',
    'Construire le cache OSM local': 'Construir caché OSM local',
    'Coordonnées et dossier de la tuile': 'Coordenadas y carpeta de la tesela',
    'Correction Patches': 'Corrección de parches',
    'Correction patches': 'Corrección de parches',
    'Corrections avancées': 'Correcciones avanzadas',
    'Courbure côte': 'Curvatura de costa',
    'Créer et ouvrir': 'Crear y abrir',
    'Créer la structure': 'Crear la estructura',
    'DSF/Imagery': 'DSF/Imágenes',
    'Delete ZL zone': 'Eliminar zona ZL',
    'Destination :': 'Destino:',
    'Données OSM de la tuile': 'Datos OSM de la tesela',
    'Dossier de sortie': 'Carpeta de salida',
    'Dossier des sources': 'Carpeta de origen',
    'Dossier enregistré.': 'Carpeta guardada.',
    'Dossiers enregistrés.': 'Carpetas guardadas.',
    'Détail de la tuile': 'Detalle de tesela',
    'Eau & Transparence': 'Agua y transparencia',
    'En attente…': 'Esperando…',
    'Enable': 'Activar',
    'Erase cached data': 'Borrar datos en caché',
    'Erreur': 'Error',
    'Erreur : ': 'Error: ',
    'Extract Mesh ': 'Extraer malla ',
    'Extract overlays': 'Extraer overlays',
    'Exécutables Windows': 'Ejecutables de Windows',
    'Fabrication Tuile': 'Construcción de tesela',
    'Fermer': 'Cerrar',
    'Fichier PBF introuvable.': 'Archivo PBF no encontrado.',
    'Fichier introuvable :': 'Archivo no encontrado:',
    'Gestion des Couleurs automatisée': 'Gestión de color automatizada',
    'Gestion des Données': 'Gestión de datos',
    'Gestion des JPG-Patch existants': 'Parches JPG existentes',
    'Imagerie': 'Imágenes',
    'Imagery:': 'Imágenes:',
    'Installer les Modules': 'Instalar módulos',
    'JOSM introuvable.': 'JOSM no encontrado.',
    'Jpeg imagery': 'Imágenes Jpeg',
    'Lacs & Rivières': 'Lagos y ríos',
    'Latitude:': 'Latitud:',
    'Load Tile Cfg ': 'Cargar cfg tesela',
    'Longitude:': 'Longitud:',
    'Make GeoTiffs': 'Crear GeoTiffs',
    'Mask data': 'Datos de máscara',
    'Masks': 'Máscaras',
    'Masques côtiers': 'Máscaras costeras',
    'Mesh': 'Malla',
    'Nom du fichier :': 'Nombre de archivo:',
    'OSM data': 'Datos OSM',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Abrir en JOSM',
    'Ouvrir dans QGIS': 'Abrir en QGIS',
    "Ouvrir dans l'éditeur": 'Abrir en el editor',
    'Ouvrir la racine Bathymétrie': 'Abrir la raíz de Batimetría',
    'Paramètres Mesh': 'Parámetros de malla',
    'Personnel': 'Personalizado',
    'Preview': 'Vista previa',
    'Preview params ': 'Parámetros de vista previa ',
    'Précédent': 'Anterior',
    'Préparer un pays': 'Preparar un país',
    'Prêt.': 'Listo.',
    'Publier': 'Publicar',
    'Qualité & Nettoyage': 'Calidad y limpieza',
    'Rafraîchir': 'Actualizar',
    'Ratio :': 'Proporción:',
    'Read per tile cfg': 'Leer cfg por tesela',
    'Recalculer': 'Recalcular',
    "Recalculer l'emprise": 'Recalcular la extensión',
    'Reload App Cfg': 'Recargar cfg app',
    'Restaurer': 'Restaurar',
    "Restaurer l'original": 'Restaurar el original',
    'Routes': 'Carreteras',
    'Réappliquer mes modifications': 'Reaplicar mis cambios',
    'SUCCÈS': 'ÉXITO',
    'Saturation:': 'Saturación:',
    'Sauvegarder mes modifications': 'Guardar mis cambios',
    'Sauvegardes': 'Copias de seguridad',
    'Scan en cours…': 'Escaneando…',
    'Shortcuts :': 'Atajos:',
    'Source : ': 'Fuente: ',
    'Strength:': 'Intensidad:',
    'Suivant': 'Siguiente',
    'Suppression dossier Preview': 'Eliminar carpeta Preview',
    'Supprimer patches sélectionnés': 'Eliminar parches seleccionados',
    'TERMINÉ.': 'HECHO.',
    'Terminé.': 'Hecho.',
    'Terrain & Ombrage': 'Terreno y sombreado',
    'Tile (textures)': 'Tesela (texturas)',
    'Tile (whole)': 'Tesela (completa)',
    'Timeline non disponible.': 'Cronología no disponible.',
    'Tous les fichiers': 'Todos los archivos',
    'Tout cocher': 'Marcar todo',
    'Tout décocher': 'Desmarcar todo',
    'Triangulate 3D Mesh': 'Triangular malla 3D',
    'Tuile active :': 'Tesela activa:',
    'Valider': 'OK',
    'Vector data': 'Datos vectoriales',
    'Visualiser la tuile': 'Ver tesela',
    'Write App Cfg ': 'Guardar cfg app',
    'Write Tile Cfg': 'Guardar cfg tesela',
    'Zone params ': 'Parámetros de zona ',
    'Zoomlevel : ': 'Nivel de zoom: ',
    'Zoomlevel:': 'Nivel de zoom:',
    'bâtiments': 'edificios',
    'indéterminée': 'indefinido',
    'introuvable': 'no encontrado',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_pt': '🇵🇹  Português',
    'language_dialog_message': 'Elija su idioma:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Cambiar idioma…',
    'language_menu_tools': 'Herramientas',
    'patches': 'parches',
    'personal_provider_deleted_ok': 'Proveedor eliminado.',
    'personal_provider_err_url': 'La URL no puede estar vacía.',
    'personal_provider_list_label': 'Mis proveedores:',
    'routes principales': 'carreteras principales',
    'routes secondaires': 'carreteras secundarias',
    'trait de côte': 'línea de costa',
    'ÉCHEC': 'FALLIDO',
    'ÉCHEC :': 'FALLÓ:',
    'Échec.': 'Falló.',
    'Écraser les fichiers de cache existants': 'Sobrescribir archivos de caché existentes',
    'à venir': 'próximamente',
    '⛰ Terrain & Relief': '⛰ Terreno y elevación',
    '🌊 Côte & Masques': '🌊 Costa y máscaras',
    '💧 Mer & Eau': '💧 Mar y agua',
    '📷 Imagerie & Aéroports': '📷 Imágenes y aeropuertos',
    '🗺 Mesh 3D': '🗺 Malla 3D',
})
