# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_DA.py  —  ORTHO4XP V3  —  Language file : DANSK
#
#  Base = engelsk : enhver nøgle der ikke er oversat nedenfor
#  falder automatisk tilbage til den engelske tekst (ingen crash,
#  ingen manglende tekst). Lange tekniske værktøjstip forbliver
#  på engelsk indtil videre og kan finpudses senere.
# ============================================================

LANG = "DA"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Afslut      ',
    '     Exit     ': '     Afslut     ',
    '    All in one     ': '    Alt i ét     ',
    '    Apply    ': '    Anvend    ',
    '    Apply     ': '    Anvend     ',
    '    Exit     ': '    Afslut     ',
    '    Refresh     ': '    Opdater     ',
    '    Reset    ': '    Nulstil    ',
    '  Batch Build   ': '  Batch-byg   ',
    '  Delete    ': '  Slet    ',
    '  Save zone  ': '  Gem zone  ',
    ' Build Imagery/DSF ': ' Byg billeder/DSF ',
    ' Draw Water Masks  ': ' Tegn vandmasker  ',
    'Active tile': 'Aktiv flise',
    'Aide JOSM': 'JOSM-hjælp',
    'Ajouter un pays': 'Tilføj et land',
    'Altimétrie & Vecteurs': 'Højdedata & vektorer',
    'Altimétrie / DEM': 'Højde / DEM',
    'Analyse…': 'Analyserer…',
    'Annuler': 'Annuller',
    'Application ': 'Applikation ',
    'Application :': 'Applikation:',
    'Applications macOS': 'macOS-applikationer',
    'Assemble Vector data': 'Sammensæt vektordata',
    'Assembler': 'Sammensæt',
    'Aucun patch sélectionné.': 'Ingen patch valgt.',
    'Aucune vignette cochée.': 'Ingen miniature valgt.',
    'Aéroport & Runways': 'Lufthavn & landingsbaner',
    'Aéroports': 'Lufthavne',
    'Base Folder:': 'Basismappe:',
    'Bathymétrie': 'Batymetri',
    'Boost:': 'Boost:',
    'Build All': 'Byg alt',
    'Chargement…': 'Indlæser…',
    'Choisir QGIS': 'Vælg QGIS',
    'Color Normalize': 'Farvenormalisering',
    'Confirmation': 'Bekræftelse',
    'Construire le cache OSM local': 'Byg lokal OSM-cache',
    'Coordonnées et dossier de la tuile': 'Flisekoordinater og mappe',
    'Correction Patches': 'Patch-korrektion',
    'Correction patches': 'Patch-korrektion',
    'Corrections avancées': 'Avancerede korrektioner',
    'Courbure côte': 'Kystlinjekurvatur',
    'Créer et ouvrir': 'Opret og åbn',
    'Créer la structure': 'Opret strukturen',
    'DSF/Imagery': 'DSF/Billeder',
    'Delete ZL zone': 'Slet ZL-zone',
    'Destination :': 'Destination:',
    'Données OSM de la tuile': 'Flisens OSM-data',
    'Dossier de sortie': 'Outputmappe',
    'Dossier des sources': 'Kildemappe',
    'Dossier enregistré.': 'Mappe gemt.',
    'Dossiers enregistrés.': 'Mapper gemt.',
    'Détail de la tuile': 'Flisedetalje',
    'Eau & Transparence': 'Vand & gennemsigtighed',
    'En attente…': 'Venter…',
    'Enable': 'Aktiver',
    'Erase cached data': 'Slet cachede data',
    'Erreur': 'Fejl',
    'Erreur : ': 'Fejl: ',
    'Extract Mesh ': 'Udtræk mesh ',
    'Extract overlays': 'Udtræk overlays',
    'Exécutables Windows': 'Windows-programmer',
    'Fabrication Tuile': 'Flisebygning',
    'Fermer': 'Luk',
    'Fichier PBF introuvable.': 'PBF-fil ikke fundet.',
    'Fichier introuvable :': 'Fil ikke fundet:',
    'Gestion des Couleurs automatisée': 'Automatisk farvestyring',
    'Gestion des Données': 'Databehandling',
    'Gestion des JPG-Patch existants': 'Eksisterende JPG-patches',
    'Imagerie': 'Billeder',
    'Imagery:': 'Billeder:',
    'Installer les Modules': 'Installer moduler',
    'JOSM introuvable.': 'JOSM ikke fundet.',
    'Jpeg imagery': 'Jpeg-billeder',
    'Lacs & Rivières': 'Søer & floder',
    'Latitude:': 'Breddegrad:',
    'Load Tile Cfg ': 'Indlæs flisekonfig',
    'Longitude:': 'Længdegrad:',
    'Make GeoTiffs': 'Lav GeoTiffs',
    'Mask data': 'Maskedata',
    'Masks': 'Masker',
    'Masques côtiers': 'Kystmasker',
    'Mesh': 'Mesh',
    'Nom du fichier :': 'Filnavn:',
    'OSM data': 'OSM-data',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Åbn i JOSM',
    'Ouvrir dans QGIS': 'Åbn i QGIS',
    "Ouvrir dans l'éditeur": 'Åbn i editor',
    'Ouvrir la racine Bathymétrie': 'Åbn Batymetri-roden',
    'Paramètres Mesh': 'Mesh-parametre',
    'Personnel': 'Brugerdefineret',
    'Preview': 'Forhåndsvisning',
    'Preview params ': 'Forhåndsvisningsparametre ',
    'Précédent': 'Forrige',
    'Préparer un pays': 'Forbered et land',
    'Prêt.': 'Klar.',
    'Publier': 'Publicer',
    'Qualité & Nettoyage': 'Kvalitet & oprydning',
    'Rafraîchir': 'Opdater',
    'Ratio :': 'Forhold:',
    'Read per tile cfg': 'Læs flisekonfig',
    'Recalculer': 'Genberegn',
    "Recalculer l'emprise": 'Genberegn udstrækningen',
    'Reload App Cfg': 'Genindlæs app-konfig',
    'Restaurer': 'Gendan',
    "Restaurer l'original": 'Gendan originalen',
    'Routes': 'Veje',
    'Réappliquer mes modifications': 'Anvend mine ændringer igen',
    'SUCCÈS': 'SUCCES',
    'Saturation:': 'Mætning:',
    'Sauvegarder mes modifications': 'Gem mine ændringer',
    'Sauvegardes': 'Sikkerhedskopier',
    'Scan en cours…': 'Scanner…',
    'Shortcuts :': 'Genveje:',
    'Source : ': 'Kilde: ',
    'Strength:': 'Styrke:',
    'Suivant': 'Næste',
    'Suppression dossier Preview': 'Slet forhåndsvisningsmappe',
    'Supprimer patches sélectionnés': 'Slet valgte patches',
    'TERMINÉ.': 'FÆRDIG.',
    'Terminé.': 'Færdig.',
    'Terrain & Ombrage': 'Terræn & skygge',
    'Tile (textures)': 'Flise (teksturer)',
    'Tile (whole)': 'Flise (hel)',
    'Timeline non disponible.': 'Tidslinje ikke tilgængelig.',
    'Tous les fichiers': 'Alle filer',
    'Tout cocher': 'Markér alle',
    'Tout décocher': 'Fjern alle markeringer',
    'Triangulate 3D Mesh': 'Triangulér 3D-mesh',
    'Tuile active :': 'Aktiv flise:',
    'Valider': 'OK',
    'Vector data': 'Vektordata',
    'Visualiser la tuile': 'Vis flise',
    'Write App Cfg ': 'Skriv app-konfig',
    'Write Tile Cfg': 'Skriv flisekonfig',
    'Zone params ': 'Zoneparametre ',
    'Zoomlevel : ': 'Zoomniveau: ',
    'Zoomlevel:': 'Zoomniveau:',
    'bâtiments': 'bygninger',
    'indéterminée': 'ubestemt',
    'introuvable': 'ikke fundet',
    'language_btn_da': '🇩🇰  Dansk',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fi': '🇫🇮  Suomi',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_gd': '🏴  Gàidhlig',
    'language_btn_is': '🇮🇸  Íslenska',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_no': '🇳🇴  Norsk',
    'language_btn_pt': '🇵🇹  Português',
    'language_btn_sv': '🇸🇪  Svenska',
    'language_dialog_message': 'Vælg dit sprog:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Skift sprog…',
    'language_menu_tools': 'Værktøjer',
    'patches': 'patches',
    'personal_provider_deleted_ok': 'Leverandør slettet.',
    'personal_provider_err_url': 'URL kan ikke være tom.',
    'personal_provider_list_label': 'Mine leverandører:',
    'routes principales': 'hovedveje',
    'routes secondaires': 'mindre veje',
    'trait de côte': 'kystlinje',
    'ÉCHEC': 'MISLYKKEDES',
    'ÉCHEC :': 'MISLYKKEDES:',
    'Échec.': 'Mislykkedes.',
    'Écraser les fichiers de cache existants': 'Overskriv eksisterende cachefiler',
    'à venir': 'kommer snart',
    '⛰ Terrain & Relief': '⛰ Terræn & relief',
    '🌊 Côte & Masques': '🌊 Kyst & masker',
    '💧 Mer & Eau': '💧 Hav & vand',
    '📷 Imagerie & Aéroports': '📷 Billeder & lufthavne',
    '🗺 Mesh 3D': '🗺 3D-mesh',
})
