# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_NL.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "NL"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Afsluiten      ',
    '     Exit     ': '     Afsluiten     ',
    '    All in one     ': '    Alles-in-één     ',
    '    Apply    ': '    Toepassen    ',
    '    Apply     ': '    Toepassen     ',
    '    Exit     ': '    Afsluiten     ',
    '    Refresh     ': '    Vernieuwen     ',
    '    Reset    ': '    Herstellen    ',
    '  Batch Build   ': '  Batch bouwen   ',
    '  Delete    ': '  Verwijderen    ',
    '  Save zone  ': '  Zone opslaan  ',
    ' Build Imagery/DSF ': ' Beelden/DSF bouwen ',
    ' Draw Water Masks  ': ' Watermaskers tekenen  ',
    'Active tile': 'Actieve tegel',
    'Aide JOSM': 'JOSM-hulp',
    'Ajouter un pays': 'Land toevoegen',
    'Altimétrie & Vecteurs': 'Hoogte & vectoren',
    'Altimétrie / DEM': 'Hoogte / DEM',
    'Analyse…': 'Analyseren…',
    'Annuler': 'Annuleren',
    'Application ': 'Toepassing ',
    'Application :': 'Toepassing:',
    'Applications macOS': 'macOS-toepassingen',
    'Assemble Vector data': 'Vectorgegevens samenstellen',
    'Assembler': 'Samenstellen',
    'Aucun patch sélectionné.': 'Geen patch geselecteerd.',
    'Aucune vignette cochée.': 'Geen miniatuur geselecteerd.',
    'Aéroport & Runways': 'Luchthaven & banen',
    'Aéroports': 'Luchthavens',
    'Base Folder:': 'Basismap:',
    'Bathymétrie': 'Bathymetrie',
    'Boost:': 'Boost:',
    'Build All': 'Alles bouwen',
    'Chargement…': 'Laden…',
    'Choisir QGIS': 'QGIS kiezen',
    'Color Normalize': 'Kleurnormalisatie',
    'Confirmation': 'Bevestiging',
    'Construire le cache OSM local': 'Lokale OSM-cache bouwen',
    'Coordonnées et dossier de la tuile': 'Tegelcoördinaten en map',
    'Correction Patches': 'Patchcorrectie',
    'Correction patches': 'Patchcorrectie',
    'Corrections avancées': 'Geavanceerde correcties',
    'Courbure côte': 'Kustkromming',
    'Créer et ouvrir': 'Maken en openen',
    'Créer la structure': 'Structuur maken',
    'DSF/Imagery': 'DSF/Beelden',
    'Delete ZL zone': 'ZL-zone verwijderen',
    'Destination :': 'Bestemming:',
    'Données OSM de la tuile': 'OSM-gegevens van de tegel',
    'Dossier de sortie': 'Uitvoermap',
    'Dossier des sources': 'Bronmap',
    'Dossier enregistré.': 'Map opgeslagen.',
    'Dossiers enregistrés.': 'Mappen opgeslagen.',
    'Détail de la tuile': 'Tegeldetail',
    'Eau & Transparence': 'Water & transparantie',
    'En attente…': 'Wachten…',
    'Enable': 'Inschakelen',
    'Erase cached data': 'Cachegegevens wissen',
    'Erreur': 'Fout',
    'Erreur : ': 'Fout: ',
    'Extract Mesh ': 'Mesh extraheren ',
    'Extract overlays': 'Overlays extraheren',
    'Exécutables Windows': 'Windows-uitvoerbare bestanden',
    'Fabrication Tuile': 'Tegel bouwen',
    'Fermer': 'Sluiten',
    'Fichier PBF introuvable.': 'PBF-bestand niet gevonden.',
    'Fichier introuvable :': 'Bestand niet gevonden:',
    'Gestion des Couleurs automatisée': 'Geautomatiseerd kleurbeheer',
    'Gestion des Données': 'Gegevensbeheer',
    'Gestion des JPG-Patch existants': 'Bestaande JPG-patches',
    'Imagerie': 'Beelden',
    'Imagery:': 'Beelden:',
    'Installer les Modules': 'Modules installeren',
    'JOSM introuvable.': 'JOSM niet gevonden.',
    'Jpeg imagery': 'Jpeg-beelden',
    'Lacs & Rivières': 'Meren & rivieren',
    'Latitude:': 'Breedte:',
    'Load Tile Cfg ': 'Tegel-cfg laden',
    'Longitude:': 'Lengte:',
    'Make GeoTiffs': 'GeoTiffs maken',
    'Mask data': 'Maskergegevens',
    'Masks': 'Maskers',
    'Masques côtiers': 'Kustmaskers',
    'Mesh': 'Mesh',
    'Nom du fichier :': 'Bestandsnaam:',
    'OSM data': 'OSM-gegevens',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Openen in JOSM',
    'Ouvrir dans QGIS': 'Openen in QGIS',
    "Ouvrir dans l'éditeur": 'Openen in editor',
    'Ouvrir la racine Bathymétrie': 'Bathymetrie-hoofdmap openen',
    'Paramètres Mesh': 'Mesh-parameters',
    'Personnel': 'Aangepast',
    'Preview': 'Voorbeeld',
    'Preview params ': 'Voorbeeldparameters ',
    'Précédent': 'Vorige',
    'Préparer un pays': 'Land voorbereiden',
    'Prêt.': 'Gereed.',
    'Publier': 'Publiceren',
    'Qualité & Nettoyage': 'Kwaliteit & opschonen',
    'Rafraîchir': 'Vernieuwen',
    'Ratio :': 'Verhouding:',
    'Read per tile cfg': 'Cfg per tegel lezen',
    'Recalculer': 'Herberekenen',
    "Recalculer l'emprise": 'Extent herberekenen',
    'Reload App Cfg': 'App-cfg herladen',
    'Restaurer': 'Herstellen',
    "Restaurer l'original": 'Origineel herstellen',
    'Routes': 'Wegen',
    'Réappliquer mes modifications': 'Mijn wijzigingen opnieuw toepassen',
    'SUCCÈS': 'SUCCES',
    'Saturation:': 'Verzadiging:',
    'Sauvegarder mes modifications': 'Mijn wijzigingen opslaan',
    'Sauvegardes': 'Back-ups',
    'Scan en cours…': 'Scannen…',
    'Shortcuts :': 'Sneltoetsen:',
    'Source : ': 'Bron: ',
    'Strength:': 'Sterkte:',
    'Suivant': 'Volgende',
    'Suppression dossier Preview': 'Preview-map verwijderen',
    'Supprimer patches sélectionnés': 'Geselecteerde patches verwijderen',
    'TERMINÉ.': 'KLAAR.',
    'Terminé.': 'Klaar.',
    'Terrain & Ombrage': 'Terrein & schaduw',
    'Tile (textures)': 'Tegel (texturen)',
    'Tile (whole)': 'Tegel (geheel)',
    'Timeline non disponible.': 'Tijdlijn niet beschikbaar.',
    'Tous les fichiers': 'Alle bestanden',
    'Tout cocher': 'Alles aanvinken',
    'Tout décocher': 'Alles uitvinken',
    'Triangulate 3D Mesh': '3D-mesh trianguleren',
    'Tuile active :': 'Actieve tegel:',
    'Valider': 'OK',
    'Vector data': 'Vectorgegevens',
    'Visualiser la tuile': 'Tegel bekijken',
    'Write App Cfg ': 'App-cfg opslaan',
    'Write Tile Cfg': 'Tegel-cfg opslaan',
    'Zone params ': 'Zoneparameters ',
    'Zoomlevel : ': 'Zoomniveau: ',
    'Zoomlevel:': 'Zoomniveau:',
    'bâtiments': 'gebouwen',
    'indéterminée': 'onbepaald',
    'introuvable': 'niet gevonden',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_pt': '🇵🇹  Português',
    'language_dialog_message': 'Kies uw taal:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Taal wijzigen…',
    'language_menu_tools': 'Hulpmiddelen',
    'patches': 'patches',
    'personal_provider_deleted_ok': 'Provider verwijderd.',
    'personal_provider_err_url': 'URL mag niet leeg zijn.',
    'personal_provider_list_label': 'Mijn providers:',
    'routes principales': 'hoofdwegen',
    'routes secondaires': 'secundaire wegen',
    'trait de côte': 'kustlijn',
    'ÉCHEC': 'MISLUKT',
    'ÉCHEC :': 'MISLUKT:',
    'Échec.': 'Mislukt.',
    'Écraser les fichiers de cache existants': 'Bestaande cachebestanden overschrijven',
    'à venir': 'binnenkort',
    '⛰ Terrain & Relief': '⛰ Terrein & hoogte',
    '🌊 Côte & Masques': '🌊 Kust & maskers',
    '💧 Mer & Eau': '💧 Zee & water',
    '📷 Imagerie & Aéroports': '📷 Beelden & luchthavens',
    '🗺 Mesh 3D': '🗺 3D-mesh',
})
