# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_GD.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "GD"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Fàg      ',
    '     Exit     ': '     Fàg     ',
    '    All in one     ': '    Na h-uile còmhla     ',
    '    Apply    ': '    Cuir an sàs    ',
    '    Apply     ': '    Cuir an sàs     ',
    '    Exit     ': '    Fàg     ',
    '    Refresh     ': '    Ath-nuadhaich     ',
    '    Reset    ': '    Ath-shuidhich    ',
    '  Batch Build   ': '  Tog baidse   ',
    '  Delete    ': '  Sguab às    ',
    '  Save zone  ': '  Sàbhail sòn  ',
    ' Build Imagery/DSF ': ' Tog ìomhaighean/DSF ',
    ' Draw Water Masks  ': ' Tarraing masgaichean-uisge  ',
    'Active tile': 'Leacag ghnìomhach',
    'Aide JOSM': 'Cuideachadh JOSM',
    'Ajouter un pays': 'Cuir dùthaich ris',
    'Altimétrie & Vecteurs': 'Àirde & vectoran',
    'Altimétrie / DEM': 'Àirde / DEM',
    'Analyse…': "A' sgrùdadh…",
    'Annuler': 'Sguir dheth',
    'Application ': 'Prògram ',
    'Application :': 'Prògram:',
    'Applications macOS': 'Prògraman macOS',
    'Assemble Vector data': 'Cruinnich dàta vector',
    'Assembler': 'Cruinnich',
    'Aucun patch sélectionné.': 'Cha deach paidse a thaghadh.',
    'Aucune vignette cochée.': 'Cha deach dealbhag a thaghadh.',
    'Aéroport & Runways': 'Port-adhair & raointean-laighe',
    'Aéroports': 'Puirt-adhair',
    'Base Folder:': 'Bun-phasgan:',
    'Bathymétrie': 'Batraiméatras',
    'Boost:': 'Boost:',
    'Build All': 'Tog na h-uile',
    'Chargement…': "A' luchdadh…",
    'Choisir QGIS': 'Tagh QGIS',
    'Color Normalize': 'Nàdarrachadh dhathan',
    'Confirmation': 'Dearbhadh',
    'Construire le cache OSM local': 'Tog tasgadh OSM ionadail',
    'Coordonnées et dossier de la tuile': 'Co-chomharran is pasgan na leacaige',
    'Correction Patches': 'Ceartachadh phaidsichean',
    'Correction patches': 'Ceartachadh phaidsichean',
    'Corrections avancées': 'Ceartachaidhean adhartach',
    'Courbure côte': 'Lùbadh na h-oirthir',
    'Créer et ouvrir': 'Cruthaich is fosgail',
    'Créer la structure': 'Cruthaich an structar',
    'DSF/Imagery': 'DSF/Ìomhaighean',
    'Delete ZL zone': 'Sguab às sòn ZL',
    'Destination :': 'Ceann-uidhe:',
    'Données OSM de la tuile': 'Dàta OSM na leacaige',
    'Dossier de sortie': 'Pasgan às-chuir',
    'Dossier des sources': 'Pasgan tùis',
    'Dossier enregistré.': 'Chaidh am pasgan a shàbhaladh.',
    'Dossiers enregistrés.': 'Chaidh na pasganan a shàbhaladh.',
    'Détail de la tuile': 'Mion-fhiosrachadh leacaige',
    'Eau & Transparence': 'Uisge & trìd-shoillseachd',
    'En attente…': "A' feitheamh…",
    'Enable': 'Cuir an comas',
    'Erase cached data': 'Sguab às dàta tasgaidh',
    'Erreur': 'Mearachd',
    'Erreur : ': 'Mearachd: ',
    'Extract Mesh ': 'Thoir a-mach mogal ',
    'Extract overlays': 'Thoir a-mach tar-chòmhdachaidhean',
    'Exécutables Windows': 'Prògraman Windows',
    'Fabrication Tuile': 'Togail leacaige',
    'Fermer': 'Dùin',
    'Fichier PBF introuvable.': 'Cha deach faidhle PBF a lorg.',
    'Fichier introuvable :': 'Cha deach am faidhle a lorg:',
    'Gestion des Couleurs automatisée': 'Riaghladh dhathan fèin-obrachail',
    'Gestion des Données': 'Riaghladh dàta',
    'Gestion des JPG-Patch existants': 'Paidsichean JPG a tha ann',
    'Imagerie': 'Ìomhaighean',
    'Imagery:': 'Ìomhaighean:',
    'Installer les Modules': 'Stàlaich mòidealan',
    'JOSM introuvable.': 'Cha deach JOSM a lorg.',
    'Jpeg imagery': 'Ìomhaighean Jpeg',
    'Lacs & Rivières': 'Lochan & aibhnichean',
    'Latitude:': 'Domhan-leud:',
    'Load Tile Cfg ': 'Luchdaich cfg leacaige',
    'Longitude:': 'Domhan-fhad:',
    'Make GeoTiffs': 'Dèan GeoTiffs',
    'Mask data': 'Dàta masg',
    'Masks': 'Masgaichean',
    'Masques côtiers': 'Masgaichean-oirthir',
    'Mesh': 'Mogal',
    'Nom du fichier :': 'Ainm faidhle:',
    'OSM data': 'Dàta OSM',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Fosgail ann an JOSM',
    'Ouvrir dans QGIS': 'Fosgail ann an QGIS',
    "Ouvrir dans l'éditeur": 'Fosgail san deasaiche',
    'Ouvrir la racine Bathymétrie': 'Fosgail bun Batraiméatras',
    'Paramètres Mesh': 'Paramadairean mogail',
    'Personnel': 'Gnàthaichte',
    'Preview': 'Ro-shealladh',
    'Preview params ': 'Paramadairean ro-shealladh ',
    'Précédent': 'Air ais',
    'Préparer un pays': 'Ullaich dùthaich',
    'Prêt.': 'Deiseil.',
    'Publier': 'Foillsich',
    'Qualité & Nettoyage': 'Càileachd & glanadh',
    'Rafraîchir': 'Ath-nuadhaich',
    'Ratio :': 'Co-mheas:',
    'Read per tile cfg': 'Leugh cfg leacaige',
    'Recalculer': 'Ath-àireamhaich',
    "Recalculer l'emprise": 'Ath-àireamhaich an ìre',
    'Reload App Cfg': 'Ath-luchdaich cfg app',
    'Restaurer': 'Aisig',
    "Restaurer l'original": 'Aisig an tè thùsail',
    'Routes': 'Rathaidean',
    'Réappliquer mes modifications': "Cuir na dh'atharraich mi an sàs a-rithist",
    'SUCCÈS': 'SOIRBHEAS',
    'Saturation:': 'Sàthachd:',
    'Sauvegarder mes modifications': "Sàbhail na dh'atharraich mi",
    'Sauvegardes': 'Lethbhreacan-glèidhidh',
    'Scan en cours…': "A' sganadh…",
    'Shortcuts :': 'Ath-ghoiridean:',
    'Source : ': 'Tùs: ',
    'Strength:': 'Neart:',
    'Suivant': 'Air adhart',
    'Suppression dossier Preview': 'Sguab às pasgan ro-shealladh',
    'Supprimer patches sélectionnés': 'Sguab às na paidsichean taghte',
    'TERMINÉ.': 'DEISEIL.',
    'Terminé.': 'Deiseil.',
    'Terrain & Ombrage': 'Talamh & sgàileadh',
    'Tile (textures)': 'Leacag (inneachan)',
    'Tile (whole)': 'Leacag (slàn)',
    'Timeline non disponible.': 'Loidhne-ama neo-ruigsinneach.',
    'Tous les fichiers': 'Na h-uile faidhle',
    'Tout cocher': 'Cuir cromag air a h-uile',
    'Tout décocher': 'Thoir cromag far a h-uile',
    'Triangulate 3D Mesh': 'Triantanaich mogal 3D',
    'Tuile active :': 'Leacag ghnìomhach:',
    'Valider': 'OK',
    'Vector data': 'Dàta vector',
    'Visualiser la tuile': 'Seall leacag',
    'Write App Cfg ': 'Sgrìobh cfg app',
    'Write Tile Cfg': 'Sgrìobh cfg leacaige',
    'Zone params ': 'Paramadairean sòn ',
    'Zoomlevel : ': 'Ìre sùmaidh: ',
    'Zoomlevel:': 'Ìre sùmaidh:',
    'bâtiments': 'togalaichean',
    'indéterminée': 'gun mhìneachadh',
    'introuvable': 'cha deach a lorg',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fi': '🇫🇮  Suomi',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_gd': '🏴  Gàidhlig',
    'language_btn_is': '🇮🇸  Íslenska',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_no': '🇳🇴  Norsk',
    'language_btn_pt': '🇵🇹  Português',
    'language_btn_sv': '🇸🇪  Svenska',
    'language_dialog_message': 'Tagh do chànan:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Atharraich cànan…',
    'language_menu_tools': 'Innealan',
    'patches': 'paidsichean',
    'personal_provider_deleted_ok': 'Chaidh an solaraiche a sguabadh às.',
    'personal_provider_err_url': 'Chan fhaod an URL a bhith falamh.',
    'personal_provider_list_label': 'Na solaraichean agam:',
    'routes principales': 'prìomh rathaidean',
    'routes secondaires': 'rathaidean beaga',
    'trait de côte': 'oirthir',
    'ÉCHEC': "DH'FHÀILLIG",
    'ÉCHEC :': "DH'FHÀILLIG:",
    'Échec.': "Dh'fhàillig.",
    'Écraser les fichiers de cache existants': 'Sgrìobh thairis air faidhlichean tasgaidh',
    'à venir': "a' tighinn a dh'aithghearr",
    '⛰ Terrain & Relief': '⛰ Talamh & àirde',
    '🌊 Côte & Masques': '🌊 Oirthir & masgaichean',
    '💧 Mer & Eau': '💧 Muir & uisge',
    '📷 Imagerie & Aéroports': '📷 Ìomhaighean & puirt-adhair',
    '🗺 Mesh 3D': '🗺 Mogal 3D',
})
