# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_IS.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "IS"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Hætta      ',
    '     Exit     ': '     Hætta     ',
    '    All in one     ': '    Allt í einu     ',
    '    Apply    ': '    Beita    ',
    '    Apply     ': '    Beita     ',
    '    Exit     ': '    Hætta     ',
    '    Refresh     ': '    Endurhlaða     ',
    '    Reset    ': '    Endurstilla    ',
    '  Batch Build   ': '  Runuvinnsla   ',
    '  Delete    ': '  Eyða    ',
    '  Save zone  ': '  Vista svæði  ',
    ' Build Imagery/DSF ': ' Byggja myndir/DSF ',
    ' Draw Water Masks  ': ' Teikna vatnsmaska  ',
    'Active tile': 'Virk flís',
    'Aide JOSM': 'JOSM-hjálp',
    'Ajouter un pays': 'Bæta við landi',
    'Altimétrie & Vecteurs': 'Hæðargögn & vigrar',
    'Altimétrie / DEM': 'Hæð / DEM',
    'Analyse…': 'Greini…',
    'Annuler': 'Hætta við',
    'Application ': 'Forrit ',
    'Application :': 'Forrit:',
    'Applications macOS': 'macOS-forrit',
    'Assemble Vector data': 'Setja saman vigurgögn',
    'Assembler': 'Setja saman',
    'Aucun patch sélectionné.': 'Engin bót valin.',
    'Aucune vignette cochée.': 'Engin smámynd valin.',
    'Aéroport & Runways': 'Flugvöllur & brautir',
    'Aéroports': 'Flugvellir',
    'Base Folder:': 'Grunnmappa:',
    'Bathymétrie': 'Dýptarmæling',
    'Boost:': 'Efling:',
    'Build All': 'Byggja allt',
    'Chargement…': 'Hleð…',
    'Choisir QGIS': 'Velja QGIS',
    'Color Normalize': 'Litajöfnun',
    'Confirmation': 'Staðfesting',
    'Construire le cache OSM local': 'Byggja staðbundið OSM-skyndiminni',
    'Coordonnées et dossier de la tuile': 'Flísahnit og mappa',
    'Correction Patches': 'Bótaleiðrétting',
    'Correction patches': 'Bótaleiðrétting',
    'Corrections avancées': 'Ítarlegar leiðréttingar',
    'Courbure côte': 'Strandlínusveigja',
    'Créer et ouvrir': 'Búa til og opna',
    'Créer la structure': 'Búa til uppbyggingu',
    'DSF/Imagery': 'DSF/Myndir',
    'Delete ZL zone': 'Eyða ZL-svæði',
    'Destination :': 'Áfangastaður:',
    'Données OSM de la tuile': 'OSM-gögn flísar',
    'Dossier de sortie': 'Úttaksmappa',
    'Dossier des sources': 'Upprunamappa',
    'Dossier enregistré.': 'Mappa vistuð.',
    'Dossiers enregistrés.': 'Möppur vistaðar.',
    'Détail de la tuile': 'Flísaupplýsingar',
    'Eau & Transparence': 'Vatn & gagnsæi',
    'En attente…': 'Bíð…',
    'Enable': 'Virkja',
    'Erase cached data': 'Eyða skyndiminni',
    'Erreur': 'Villa',
    'Erreur : ': 'Villa: ',
    'Extract Mesh ': 'Draga út möskva ',
    'Extract overlays': 'Draga út yfirlög',
    'Exécutables Windows': 'Windows-keyrsluskrár',
    'Fabrication Tuile': 'Flísabygging',
    'Fermer': 'Loka',
    'Fichier PBF introuvable.': 'PBF-skrá fannst ekki.',
    'Fichier introuvable :': 'Skrá fannst ekki:',
    'Gestion des Couleurs automatisée': 'Sjálfvirk litastjórnun',
    'Gestion des Données': 'Gagnastjórnun',
    'Gestion des JPG-Patch existants': 'Núverandi JPG-bætur',
    'Imagerie': 'Myndir',
    'Imagery:': 'Myndir:',
    'Installer les Modules': 'Setja upp einingar',
    'JOSM introuvable.': 'JOSM fannst ekki.',
    'Jpeg imagery': 'Jpeg-myndir',
    'Lacs & Rivières': 'Vötn & ár',
    'Latitude:': 'Breidd:',
    'Load Tile Cfg ': 'Hlaða flísastill.',
    'Longitude:': 'Lengd:',
    'Make GeoTiffs': 'Búa til GeoTiffs',
    'Mask data': 'Maskagögn',
    'Masks': 'Maskar',
    'Masques côtiers': 'Strandmaskar',
    'Mesh': 'Möskvi',
    'Nom du fichier :': 'Skráarnafn:',
    'OSM data': 'OSM-gögn',
    'Ok': 'Í lagi',
    'Ouvrir dans JOSM': 'Opna í JOSM',
    'Ouvrir dans QGIS': 'Opna í QGIS',
    "Ouvrir dans l'éditeur": 'Opna í ritli',
    'Ouvrir la racine Bathymétrie': 'Opna Dýptarmælingarót',
    'Paramètres Mesh': 'Möskvastillingar',
    'Personnel': 'Sérsniðið',
    'Preview': 'Forskoðun',
    'Preview params ': 'Forskoðunarstillingar ',
    'Précédent': 'Fyrri',
    'Préparer un pays': 'Undirbúa land',
    'Prêt.': 'Tilbúið.',
    'Publier': 'Birta',
    'Qualité & Nettoyage': 'Gæði & hreinsun',
    'Rafraîchir': 'Endurhlaða',
    'Ratio :': 'Hlutfall:',
    'Read per tile cfg': 'Lesa flísastill.',
    'Recalculer': 'Endurreikna',
    "Recalculer l'emprise": 'Endurreikna útbreiðslu',
    'Reload App Cfg': 'Endurhlaða forr.still.',
    'Restaurer': 'Endurheimta',
    "Restaurer l'original": 'Endurheimta upprunalegt',
    'Routes': 'Vegir',
    'Réappliquer mes modifications': 'Beita breytingum aftur',
    'SUCCÈS': 'TÓKST',
    'Saturation:': 'Mettun:',
    'Sauvegarder mes modifications': 'Vista breytingar mínar',
    'Sauvegardes': 'Afrit',
    'Scan en cours…': 'Skanna…',
    'Shortcuts :': 'Flýtileiðir:',
    'Source : ': 'Uppspretta: ',
    'Strength:': 'Styrkur:',
    'Suivant': 'Næsta',
    'Suppression dossier Preview': 'Eyða forskoðunarmöppu',
    'Supprimer patches sélectionnés': 'Eyða völdum bótum',
    'TERMINÉ.': 'LOKIÐ.',
    'Terminé.': 'Lokið.',
    'Terrain & Ombrage': 'Landslag & skygging',
    'Tile (textures)': 'Flís (áferðir)',
    'Tile (whole)': 'Flís (öll)',
    'Timeline non disponible.': 'Tímalína ekki tiltæk.',
    'Tous les fichiers': 'Allar skrár',
    'Tout cocher': 'Velja allt',
    'Tout décocher': 'Afvelja allt',
    'Triangulate 3D Mesh': 'Þríhyrna 3D-möskva',
    'Tuile active :': 'Virk flís:',
    'Valider': 'Í lagi',
    'Vector data': 'Vigurgögn',
    'Visualiser la tuile': 'Skoða flís',
    'Write App Cfg ': 'Vista forr.still.',
    'Write Tile Cfg': 'Vista flísastill.',
    'Zone params ': 'Svæðisstillingar ',
    'Zoomlevel : ': 'Aðdráttarstig: ',
    'Zoomlevel:': 'Aðdráttarstig:',
    'bâtiments': 'byggingar',
    'indéterminée': 'óskilgreint',
    'introuvable': 'fannst ekki',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fi': '🇫🇮  Suomi',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_gd': '🏴  Gàidhlig',
    'language_btn_is': '🇮🇸  Íslenska',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_no': '🇳🇴  Norsk',
    'language_btn_pt': '🇵🇹  Português',
    'language_btn_sv': '🇸🇪  Svenska',
    'language_dialog_message': 'Veldu tungumál:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Breyta tungumáli…',
    'language_menu_tools': 'Verkfæri',
    'patches': 'bætur',
    'personal_provider_deleted_ok': 'Veitanda eytt.',
    'personal_provider_err_url': 'Vefslóð má ekki vera tóm.',
    'personal_provider_list_label': 'Mínir veitendur:',
    'routes principales': 'aðalvegir',
    'routes secondaires': 'hliðarvegir',
    'trait de côte': 'strandlína',
    'ÉCHEC': 'MISTÓKST',
    'ÉCHEC :': 'MISTÓKST:',
    'Échec.': 'Mistókst.',
    'Écraser les fichiers de cache existants': 'Skrifa yfir skyndiminnisskrár',
    'à venir': 'væntanlegt',
    '⛰ Terrain & Relief': '⛰ Landslag & hæð',
    '🌊 Côte & Masques': '🌊 Strönd & maskar',
    '💧 Mer & Eau': '💧 Sjór & vatn',
    '📷 Imagerie & Aéroports': '📷 Myndir & flugvellir',
    '🗺 Mesh 3D': '🗺 3D-möskvi',
})
