# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_PT.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "PT"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Sair      ',
    '     Exit     ': '     Sair     ',
    '    All in one     ': '    Tudo em um     ',
    '    Apply    ': '    Aplicar    ',
    '    Apply     ': '    Aplicar     ',
    '    Exit     ': '    Sair     ',
    '    Refresh     ': '    Atualizar     ',
    '    Reset    ': '    Repor    ',
    '  Batch Build   ': '  Construir em lote   ',
    '  Delete    ': '  Eliminar    ',
    '  Save zone  ': '  Guardar zona  ',
    ' Build Imagery/DSF ': ' Construir imagens/DSF ',
    ' Draw Water Masks  ': ' Desenhar máscaras de água  ',
    'Active tile': 'Tile ativo',
    'Aide JOSM': 'Ajuda do JOSM',
    'Ajouter un pays': 'Adicionar um país',
    'Altimétrie & Vecteurs': 'Altimetria e vetores',
    'Altimétrie / DEM': 'Elevação / DEM',
    'Analyse…': 'A analisar…',
    'Annuler': 'Cancelar',
    'Application ': 'Aplicação ',
    'Application :': 'Aplicação:',
    'Applications macOS': 'Aplicações macOS',
    'Assemble Vector data': 'Montar dados vetoriais',
    'Assembler': 'Montar',
    'Aucun patch sélectionné.': 'Nenhum patch selecionado.',
    'Aucune vignette cochée.': 'Nenhuma miniatura selecionada.',
    'Aéroport & Runways': 'Aeroporto e pistas',
    'Aéroports': 'Aeroportos',
    'Base Folder:': 'Pasta base:',
    'Bathymétrie': 'Batimetria',
    'Boost:': 'Reforço:',
    'Build All': 'Construir tudo',
    'Chargement…': 'A carregar…',
    'Choisir QGIS': 'Escolher QGIS',
    'Color Normalize': 'Normalizar cor',
    'Confirmation': 'Confirmação',
    'Construire le cache OSM local': 'Construir cache OSM local',
    'Coordonnées et dossier de la tuile': 'Coordenadas e pasta do tile',
    'Correction Patches': 'Correção de patches',
    'Correction patches': 'Correção de patches',
    'Corrections avancées': 'Correções avançadas',
    'Courbure côte': 'Curvatura da costa',
    'Créer et ouvrir': 'Criar e abrir',
    'Créer la structure': 'Criar a estrutura',
    'DSF/Imagery': 'DSF/Imagens',
    'Delete ZL zone': 'Eliminar zona ZL',
    'Destination :': 'Destino:',
    'Données OSM de la tuile': 'Dados OSM do tile',
    'Dossier de sortie': 'Pasta de saída',
    'Dossier des sources': 'Pasta de origem',
    'Dossier enregistré.': 'Pasta guardada.',
    'Dossiers enregistrés.': 'Pastas guardadas.',
    'Détail de la tuile': 'Detalhe do tile',
    'Eau & Transparence': 'Água e transparência',
    'En attente…': 'A aguardar…',
    'Enable': 'Ativar',
    'Erase cached data': 'Apagar dados em cache',
    'Erreur': 'Erro',
    'Erreur : ': 'Erro: ',
    'Extract Mesh ': 'Extrair malha ',
    'Extract overlays': 'Extrair overlays',
    'Exécutables Windows': 'Executáveis Windows',
    'Fabrication Tuile': 'Construção de tile',
    'Fermer': 'Fechar',
    'Fichier PBF introuvable.': 'Ficheiro PBF não encontrado.',
    'Fichier introuvable :': 'Ficheiro não encontrado:',
    'Gestion des Couleurs automatisée': 'Gestão de cor automatizada',
    'Gestion des Données': 'Gestão de dados',
    'Gestion des JPG-Patch existants': 'Patches JPG existentes',
    'Imagerie': 'Imagens',
    'Imagery:': 'Imagens:',
    'Installer les Modules': 'Instalar módulos',
    'JOSM introuvable.': 'JOSM não encontrado.',
    'Jpeg imagery': 'Imagens Jpeg',
    'Lacs & Rivières': 'Lagos e rios',
    'Latitude:': 'Latitude:',
    'Load Tile Cfg ': 'Carregar cfg do tile',
    'Longitude:': 'Longitude:',
    'Make GeoTiffs': 'Criar GeoTiffs',
    'Mask data': 'Dados de máscara',
    'Masks': 'Máscaras',
    'Masques côtiers': 'Máscaras costeiras',
    'Mesh': 'Malha',
    'Nom du fichier :': 'Nome do ficheiro:',
    'OSM data': 'Dados OSM',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Abrir no JOSM',
    'Ouvrir dans QGIS': 'Abrir no QGIS',
    "Ouvrir dans l'éditeur": 'Abrir no editor',
    'Ouvrir la racine Bathymétrie': 'Abrir a raiz de Batimetria',
    'Paramètres Mesh': 'Parâmetros da malha',
    'Personnel': 'Personalizado',
    'Preview': 'Pré-visualização',
    'Preview params ': 'Parâmetros de pré-visualização ',
    'Précédent': 'Anterior',
    'Préparer un pays': 'Preparar um país',
    'Prêt.': 'Pronto.',
    'Publier': 'Publicar',
    'Qualité & Nettoyage': 'Qualidade e limpeza',
    'Rafraîchir': 'Atualizar',
    'Ratio :': 'Rácio:',
    'Read per tile cfg': 'Ler cfg por tile',
    'Recalculer': 'Recalcular',
    "Recalculer l'emprise": 'Recalcular a extensão',
    'Reload App Cfg': 'Recarregar cfg da app',
    'Restaurer': 'Restaurar',
    "Restaurer l'original": 'Restaurar o original',
    'Routes': 'Estradas',
    'Réappliquer mes modifications': 'Reaplicar as minhas alterações',
    'SUCCÈS': 'SUCESSO',
    'Saturation:': 'Saturação:',
    'Sauvegarder mes modifications': 'Guardar as minhas alterações',
    'Sauvegardes': 'Cópias de segurança',
    'Scan en cours…': 'A analisar…',
    'Shortcuts :': 'Atalhos:',
    'Source : ': 'Fonte: ',
    'Strength:': 'Intensidade:',
    'Suivant': 'Seguinte',
    'Suppression dossier Preview': 'Eliminar pasta Preview',
    'Supprimer patches sélectionnés': 'Eliminar patches selecionados',
    'TERMINÉ.': 'CONCLUÍDO.',
    'Terminé.': 'Concluído.',
    'Terrain & Ombrage': 'Terreno e sombreado',
    'Tile (textures)': 'Tile (texturas)',
    'Tile (whole)': 'Tile (inteiro)',
    'Timeline non disponible.': 'Cronologia não disponível.',
    'Tous les fichiers': 'Todos os ficheiros',
    'Tout cocher': 'Selecionar tudo',
    'Tout décocher': 'Desmarcar tudo',
    'Triangulate 3D Mesh': 'Triangular malha 3D',
    'Tuile active :': 'Tile ativo:',
    'Valider': 'OK',
    'Vector data': 'Dados vetoriais',
    'Visualiser la tuile': 'Ver tile',
    'Write App Cfg ': 'Gravar cfg da app',
    'Write Tile Cfg': 'Gravar cfg do tile',
    'Zone params ': 'Parâmetros de zona ',
    'Zoomlevel : ': 'Nível de zoom: ',
    'Zoomlevel:': 'Nível de zoom:',
    'bâtiments': 'edifícios',
    'indéterminée': 'indefinido',
    'introuvable': 'não encontrado',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_pt': '🇵🇹  Português',
    'language_dialog_message': 'Escolha o seu idioma:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Mudar idioma…',
    'language_menu_tools': 'Ferramentas',
    'patches': 'patches',
    'personal_provider_deleted_ok': 'Fornecedor eliminado.',
    'personal_provider_err_url': 'O URL não pode estar vazio.',
    'personal_provider_list_label': 'Os meus fornecedores:',
    'routes principales': 'estradas principais',
    'routes secondaires': 'estradas secundárias',
    'trait de côte': 'linha de costa',
    'ÉCHEC': 'FALHOU',
    'ÉCHEC :': 'FALHOU:',
    'Échec.': 'Falhou.',
    'Écraser les fichiers de cache existants': 'Substituir ficheiros de cache existentes',
    'à venir': 'em breve',
    '⛰ Terrain & Relief': '⛰ Terreno e elevação',
    '🌊 Côte & Masques': '🌊 Costa e máscaras',
    '💧 Mer & Eau': '💧 Mar e água',
    '📷 Imagerie & Aéroports': '📷 Imagens e aeroportos',
    '🗺 Mesh 3D': '🗺 Malha 3D',
})
