# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_DE.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "DE"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Beenden      ',
    '     Exit     ': '     Beenden     ',
    '    All in one     ': '    Alles in einem     ',
    '    Apply    ': '    Anwenden    ',
    '    Apply     ': '    Anwenden     ',
    '    Exit     ': '    Beenden     ',
    '    Refresh     ': '    Aktualisieren     ',
    '    Reset    ': '    Zurücksetzen    ',
    '  Batch Build   ': '  Stapel erstellen   ',
    '  Delete    ': '  Löschen    ',
    '  Save zone  ': '  Zone speichern  ',
    ' Build Imagery/DSF ': ' Bilddaten/DSF erstellen ',
    ' Draw Water Masks  ': ' Wassermasken zeichnen  ',
    'Active tile': 'Aktive Kachel',
    'Aide JOSM': 'JOSM-Hilfe',
    'Ajouter un pays': 'Land hinzufügen',
    'Altimétrie & Vecteurs': 'Höhendaten & Vektoren',
    'Altimétrie / DEM': 'Höhe / DEM',
    'Analyse…': 'Wird analysiert…',
    'Annuler': 'Abbrechen',
    'Application ': 'Anwendung ',
    'Application :': 'Anwendung:',
    'Applications macOS': 'macOS-Anwendungen',
    'Assemble Vector data': 'Vektordaten zusammenführen',
    'Assembler': 'Zusammenführen',
    'Aucun patch sélectionné.': 'Kein Patch ausgewählt.',
    'Aucune vignette cochée.': 'Kein Miniaturbild ausgewählt.',
    'Aéroport & Runways': 'Flughafen & Pisten',
    'Aéroports': 'Flughäfen',
    'Base Folder:': 'Basisordner:',
    'Bathymétrie': 'Bathymetrie',
    'Boost:': 'Verstärkung:',
    'Build All': 'Alles erstellen',
    'Chargement…': 'Wird geladen…',
    'Choisir QGIS': 'QGIS wählen',
    'Color Normalize': 'Farbnormalisierung',
    'Confirmation': 'Bestätigung',
    'Construire le cache OSM local': 'Lokalen OSM-Cache erstellen',
    'Coordonnées et dossier de la tuile': 'Kachelkoordinaten und Ordner',
    'Correction Patches': 'Patch-Korrektur',
    'Correction patches': 'Patch-Korrektur',
    'Corrections avancées': 'Erweiterte Korrekturen',
    'Courbure côte': 'Küstenkrümmung',
    'Créer et ouvrir': 'Erstellen und öffnen',
    'Créer la structure': 'Struktur erstellen',
    'DSF/Imagery': 'DSF/Bilddaten',
    'Delete ZL zone': 'ZL-Zone löschen',
    'Destination :': 'Ziel:',
    'Données OSM de la tuile': 'OSM-Daten der Kachel',
    'Dossier de sortie': 'Ausgabeordner',
    'Dossier des sources': 'Quellordner',
    'Dossier enregistré.': 'Ordner gespeichert.',
    'Dossiers enregistrés.': 'Ordner gespeichert.',
    'Détail de la tuile': 'Kacheldetail',
    'Eau & Transparence': 'Wasser & Transparenz',
    'En attente…': 'Warten…',
    'Enable': 'Aktivieren',
    'Erase cached data': 'Zwischenspeicher löschen',
    'Erreur': 'Fehler',
    'Erreur : ': 'Fehler: ',
    'Extract Mesh ': 'Mesh extrahieren ',
    'Extract overlays': 'Overlays extrahieren',
    'Exécutables Windows': 'Windows-Programme',
    'Fabrication Tuile': 'Kachelerstellung',
    'Fermer': 'Schließen',
    'Fichier PBF introuvable.': 'PBF-Datei nicht gefunden.',
    'Fichier introuvable :': 'Datei nicht gefunden:',
    'Gestion des Couleurs automatisée': 'Automatische Farbverwaltung',
    'Gestion des Données': 'Datenverwaltung',
    'Gestion des JPG-Patch existants': 'Vorhandene JPG-Patches',
    'Imagerie': 'Bilddaten',
    'Imagery:': 'Bilddaten:',
    'Installer les Modules': 'Module installieren',
    'JOSM introuvable.': 'JOSM nicht gefunden.',
    'Jpeg imagery': 'Jpeg-Bilddaten',
    'Lacs & Rivières': 'Seen & Flüsse',
    'Latitude:': 'Breite:',
    'Load Tile Cfg ': 'Kachel-Cfg laden',
    'Longitude:': 'Länge:',
    'Make GeoTiffs': 'GeoTiffs erstellen',
    'Mask data': 'Maskendaten',
    'Masks': 'Masken',
    'Masques côtiers': 'Küstenmasken',
    'Mesh': 'Mesh',
    'Nom du fichier :': 'Dateiname:',
    'OSM data': 'OSM-Daten',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'In JOSM öffnen',
    'Ouvrir dans QGIS': 'In QGIS öffnen',
    "Ouvrir dans l'éditeur": 'Im Editor öffnen',
    'Ouvrir la racine Bathymétrie': 'Bathymetrie-Wurzel öffnen',
    'Paramètres Mesh': 'Mesh-Parameter',
    'Personnel': 'Benutzerdefiniert',
    'Preview': 'Vorschau',
    'Preview params ': 'Vorschauparameter ',
    'Précédent': 'Zurück',
    'Préparer un pays': 'Land vorbereiten',
    'Prêt.': 'Bereit.',
    'Publier': 'Veröffentlichen',
    'Qualité & Nettoyage': 'Qualität & Bereinigung',
    'Rafraîchir': 'Aktualisieren',
    'Ratio :': 'Verhältnis:',
    'Read per tile cfg': 'Kachel-Cfg lesen',
    'Recalculer': 'Neu berechnen',
    "Recalculer l'emprise": 'Ausdehnung neu berechnen',
    'Reload App Cfg': 'App-Cfg neu laden',
    'Restaurer': 'Wiederherstellen',
    "Restaurer l'original": 'Original wiederherstellen',
    'Routes': 'Straßen',
    'Réappliquer mes modifications': 'Meine Änderungen erneut anwenden',
    'SUCCÈS': 'ERFOLG',
    'Saturation:': 'Sättigung:',
    'Sauvegarder mes modifications': 'Meine Änderungen speichern',
    'Sauvegardes': 'Sicherungen',
    'Scan en cours…': 'Wird gescannt…',
    'Shortcuts :': 'Tastenkürzel:',
    'Source : ': 'Quelle: ',
    'Strength:': 'Stärke:',
    'Suivant': 'Weiter',
    'Suppression dossier Preview': 'Vorschauordner löschen',
    'Supprimer patches sélectionnés': 'Ausgewählte Patches löschen',
    'TERMINÉ.': 'FERTIG.',
    'Terminé.': 'Fertig.',
    'Terrain & Ombrage': 'Gelände & Schattierung',
    'Tile (textures)': 'Kachel (Texturen)',
    'Tile (whole)': 'Kachel (ganz)',
    'Timeline non disponible.': 'Timeline nicht verfügbar.',
    'Tous les fichiers': 'Alle Dateien',
    'Tout cocher': 'Alle auswählen',
    'Tout décocher': 'Alle abwählen',
    'Triangulate 3D Mesh': '3D-Mesh triangulieren',
    'Tuile active :': 'Aktive Kachel:',
    'Valider': 'OK',
    'Vector data': 'Vektordaten',
    'Visualiser la tuile': 'Kachel anzeigen',
    'Write App Cfg ': 'App-Cfg schreiben',
    'Write Tile Cfg': 'Kachel-Cfg schreiben',
    'Zone params ': 'Zonenparameter ',
    'Zoomlevel : ': 'Zoomstufe: ',
    'Zoomlevel:': 'Zoomstufe:',
    'bâtiments': 'Gebäude',
    'indéterminée': 'unbestimmt',
    'introuvable': 'nicht gefunden',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_pt': '🇵🇹  Português',
    'language_dialog_message': 'Wählen Sie Ihre Sprache:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Sprache ändern…',
    'language_menu_tools': 'Werkzeuge',
    'patches': 'Patches',
    'personal_provider_deleted_ok': 'Anbieter gelöscht.',
    'personal_provider_err_url': 'URL darf nicht leer sein.',
    'personal_provider_list_label': 'Meine Anbieter:',
    'routes principales': 'Hauptstraßen',
    'routes secondaires': 'Nebenstraßen',
    'trait de côte': 'Küstenlinie',
    'ÉCHEC': 'FEHLGESCHLAGEN',
    'ÉCHEC :': 'FEHLGESCHLAGEN:',
    'Échec.': 'Fehlgeschlagen.',
    'Écraser les fichiers de cache existants': 'Vorhandene Cache-Dateien überschreiben',
    'à venir': 'in Kürze',
    '⛰ Terrain & Relief': '⛰ Gelände & Höhe',
    '🌊 Côte & Masques': '🌊 Küste & Masken',
    '💧 Mer & Eau': '💧 Meer & Wasser',
    '📷 Imagerie & Aéroports': '📷 Bilddaten & Flughäfen',
    '🗺 Mesh 3D': '🗺 3D-Mesh',
})
