# -*- coding: utf-8 -*-
# ============================================================
#  O4_Lang_IT.py  —  ORTHO4XP V3  —  Language file
#
#  Base = anglais : toute cle non traduite ci-dessous retombe
#  automatiquement sur le texte anglais (aucun crash, aucun
#  texte manquant). Les info-bulles techniques longues restent
#  en anglais pour l'instant et pourront etre affinees plus tard.
# ============================================================

LANG = "IT"

from O4_Lang_EN import T as _EN
T = dict(_EN)
T.update({
    '      Exit      ': '      Esci      ',
    '     Exit     ': '     Esci     ',
    '    All in one     ': '    Tutto in uno     ',
    '    Apply    ': '    Applica    ',
    '    Apply     ': '    Applica     ',
    '    Exit     ': '    Esci     ',
    '    Refresh     ': '    Aggiorna     ',
    '    Reset    ': '    Reimposta    ',
    '  Batch Build   ': '  Costruzione batch   ',
    '  Delete    ': '  Elimina    ',
    '  Save zone  ': '  Salva zona  ',
    ' Build Imagery/DSF ': ' Crea immagini/DSF ',
    ' Draw Water Masks  ': " Disegna maschere d'acqua  ",
    'Active tile': 'Tile attiva',
    'Aide JOSM': 'Guida JOSM',
    'Ajouter un pays': 'Aggiungi un paese',
    'Altimétrie & Vecteurs': 'Altimetria e vettori',
    'Altimétrie / DEM': 'Quota / DEM',
    'Analyse…': 'Analisi…',
    'Annuler': 'Annulla',
    'Application ': 'Applicazione ',
    'Application :': 'Applicazione:',
    'Applications macOS': 'Applicazioni macOS',
    'Assemble Vector data': 'Assembla dati vettoriali',
    'Assembler': 'Assembla',
    'Aucun patch sélectionné.': 'Nessun patch selezionato.',
    'Aucune vignette cochée.': 'Nessuna miniatura selezionata.',
    'Aéroport & Runways': 'Aeroporto e piste',
    'Aéroports': 'Aeroporti',
    'Base Folder:': 'Cartella base:',
    'Bathymétrie': 'Batimetria',
    'Boost:': 'Boost:',
    'Build All': 'Costruisci tutto',
    'Chargement…': 'Caricamento…',
    'Choisir QGIS': 'Scegli QGIS',
    'Color Normalize': 'Normalizza colore',
    'Confirmation': 'Conferma',
    'Construire le cache OSM local': 'Crea cache OSM locale',
    'Coordonnées et dossier de la tuile': 'Coordinate e cartella del tile',
    'Correction Patches': 'Correzione patch',
    'Correction patches': 'Correzione patch',
    'Corrections avancées': 'Correzioni avanzate',
    'Courbure côte': 'Curvatura costa',
    'Créer et ouvrir': 'Crea e apri',
    'Créer la structure': 'Crea la struttura',
    'DSF/Imagery': 'DSF/Immagini',
    'Delete ZL zone': 'Elimina zona ZL',
    'Destination :': 'Destinazione:',
    'Données OSM de la tuile': 'Dati OSM del tile',
    'Dossier de sortie': 'Cartella di output',
    'Dossier des sources': 'Cartella sorgente',
    'Dossier enregistré.': 'Cartella salvata.',
    'Dossiers enregistrés.': 'Cartelle salvate.',
    'Détail de la tuile': 'Dettaglio tile',
    'Eau & Transparence': 'Acqua e trasparenza',
    'En attente…': 'In attesa…',
    'Enable': 'Attiva',
    'Erase cached data': 'Cancella dati in cache',
    'Erreur': 'Errore',
    'Erreur : ': 'Errore: ',
    'Extract Mesh ': 'Estrai mesh ',
    'Extract overlays': 'Estrai overlay',
    'Exécutables Windows': 'Eseguibili Windows',
    'Fabrication Tuile': 'Costruzione tile',
    'Fermer': 'Chiudi',
    'Fichier PBF introuvable.': 'File PBF non trovato.',
    'Fichier introuvable :': 'File non trovato:',
    'Gestion des Couleurs automatisée': 'Gestione colore automatizzata',
    'Gestion des Données': 'Gestione dati',
    'Gestion des JPG-Patch existants': 'Patch JPG esistenti',
    'Imagerie': 'Immagini',
    'Imagery:': 'Immagini:',
    'Installer les Modules': 'Installa moduli',
    'JOSM introuvable.': 'JOSM non trovato.',
    'Jpeg imagery': 'Immagini Jpeg',
    'Lacs & Rivières': 'Laghi e fiumi',
    'Latitude:': 'Latitudine:',
    'Load Tile Cfg ': 'Carica cfg tile',
    'Longitude:': 'Longitudine:',
    'Make GeoTiffs': 'Crea GeoTiff',
    'Mask data': 'Dati maschera',
    'Masks': 'Maschere',
    'Masques côtiers': 'Maschere costiere',
    'Mesh': 'Mesh',
    'Nom du fichier :': 'Nome file:',
    'OSM data': 'Dati OSM',
    'Ok': 'OK',
    'Ouvrir dans JOSM': 'Apri in JOSM',
    'Ouvrir dans QGIS': 'Apri in QGIS',
    "Ouvrir dans l'éditeur": "Apri nell'editor",
    'Ouvrir la racine Bathymétrie': 'Apri la radice Batimetria',
    'Paramètres Mesh': 'Parametri mesh',
    'Personnel': 'Personalizzato',
    'Preview': 'Anteprima',
    'Preview params ': 'Parametri anteprima ',
    'Précédent': 'Precedente',
    'Préparer un pays': 'Prepara un paese',
    'Prêt.': 'Pronto.',
    'Publier': 'Pubblica',
    'Qualité & Nettoyage': 'Qualità e pulizia',
    'Rafraîchir': 'Aggiorna',
    'Ratio :': 'Rapporto:',
    'Read per tile cfg': 'Leggi cfg per tile',
    'Recalculer': 'Ricalcola',
    "Recalculer l'emprise": "Ricalcola l'estensione",
    'Reload App Cfg': 'Ricarica cfg app',
    'Restaurer': 'Ripristina',
    "Restaurer l'original": "Ripristina l'originale",
    'Routes': 'Strade',
    'Réappliquer mes modifications': 'Riapplica le mie modifiche',
    'SUCCÈS': 'SUCCESSO',
    'Saturation:': 'Saturazione:',
    'Sauvegarder mes modifications': 'Salva le mie modifiche',
    'Sauvegardes': 'Backup',
    'Scan en cours…': 'Scansione…',
    'Shortcuts :': 'Scorciatoie:',
    'Source : ': 'Sorgente: ',
    'Strength:': 'Intensità:',
    'Suivant': 'Avanti',
    'Suppression dossier Preview': 'Elimina cartella Preview',
    'Supprimer patches sélectionnés': 'Elimina patch selezionati',
    'TERMINÉ.': 'FATTO.',
    'Terminé.': 'Fatto.',
    'Terrain & Ombrage': 'Terreno e ombreggiatura',
    'Tile (textures)': 'Tile (texture)',
    'Tile (whole)': 'Tile (intero)',
    'Timeline non disponible.': 'Timeline non disponibile.',
    'Tous les fichiers': 'Tutti i file',
    'Tout cocher': 'Seleziona tutto',
    'Tout décocher': 'Deseleziona tutto',
    'Triangulate 3D Mesh': 'Triangola mesh 3D',
    'Tuile active :': 'Tile attivo:',
    'Valider': 'OK',
    'Vector data': 'Dati vettoriali',
    'Visualiser la tuile': 'Visualizza tile',
    'Write App Cfg ': 'Salva cfg app',
    'Write Tile Cfg': 'Salva cfg tile',
    'Zone params ': 'Parametri zona ',
    'Zoomlevel : ': 'Livello di zoom: ',
    'Zoomlevel:': 'Livello di zoom:',
    'bâtiments': 'edifici',
    'indéterminée': 'indefinito',
    'introuvable': 'non trovato',
    'language_btn_de': '🇩🇪  Deutsch',
    'language_btn_en': '🇬🇧  English',
    'language_btn_es': '🇪🇸  Español',
    'language_btn_fr': '🇫🇷  Français',
    'language_btn_it': '🇮🇹  Italiano',
    'language_btn_nl': '🇳🇱  Nederlands',
    'language_btn_pt': '🇵🇹  Português',
    'language_dialog_message': 'Scegli la lingua:',
    'language_dialog_title': 'Language / Langue',
    'language_menu_change_lang': 'Cambia lingua…',
    'language_menu_tools': 'Strumenti',
    'patches': 'patch',
    'personal_provider_deleted_ok': 'Provider eliminato.',
    'personal_provider_err_url': "L'URL non può essere vuoto.",
    'personal_provider_list_label': 'I miei provider:',
    'routes principales': 'strade principali',
    'routes secondaires': 'strade secondarie',
    'trait de côte': 'linea di costa',
    'ÉCHEC': 'NON RIUSCITO',
    'ÉCHEC :': 'NON RIUSCITO:',
    'Échec.': 'Non riuscito.',
    'Écraser les fichiers de cache existants': 'Sovrascrivi i file di cache esistenti',
    'à venir': 'prossimamente',
    '⛰ Terrain & Relief': '⛰ Terreno e quota',
    '🌊 Côte & Masques': '🌊 Costa e maschere',
    '💧 Mer & Eau': '💧 Mare e acqua',
    '📷 Imagerie & Aéroports': '📷 Immagini e aeroporti',
    '🗺 Mesh 3D': '🗺 Mesh 3D',
})
